SAP/stewardci-core

- docs/secrets/Secrets.md
Field `kind` in example snippets is wrong.
> fix secrets docs

- backend-k8s/steward-system/300_clusterTask_steward-jenkinsfile-runner.yaml
Found the follwing message in the tekton taskrun.
message: 'invalid input params: param types don''t match the user-specified
type: [RUN_NAMESPACE PIPELINE_GIT_URL PIPELINE_GIT_REVISION PIPELINE_FILE
PIPELINE_PARAMS_JSON PIPELINE_LOG_ELASTICSEARCH_INDEX_URL]'
> add mandatory type for new tekton version

- docs/backend-api/README.md
- pkg/apis/steward/v1alpha1/run_types.go
- pkg/runctl/controller.go
- Reword: Use 'abort' instead of 'kill'.
- Do not change status of completed pipeline run if
`spec.intent` is set to `abort`.
- Add API documentation.
> improve PipelineRun intent

- pkg/k8s/serviceAccountManager.go
- pkg/runctl/run_manager.go
Currently a service account `run-bot` is used for the Jenkinsfile Runner
pod, while the `default` service account of the run namespace has no
permissions.
Pipeline implementations might need to start additional pods that should
have the same cluster API access as the JFR pod. To do so, they must
specify `run-bot` as the pod's `spec.serviceAccountName`. Omitting the
field results in running the additional pod as the `default` service
account, which has no cluster API permissions. This is considered as a
common mistake and should be avoided.
If we use the `default` service account instead of `run-bot` (having the
same permissions assigned as `run-bot` had; run JFR pod as `default`
service account), pipeline implementations don't have to deal with the
service account name when starting …
> runctl: run JFR container with service account 'default'

- pkg/apis/steward/v1alpha1/run_types.go
- pkg/k8s/pipelineRun.go
- pkg/k8s/pipelineRun_test.go
- pkg/runctl/controller_test.go
introduce fields
- startedAt for timestamp when pipeline run is first touched by the controller
- finishedAt for timestamp when pipeline run result is available
introduce state pickup as first element in the history recording the time
from pipeline run creation until first touch by the controller
> improve state

- pkg/apis/steward/v1alpha1/run_types.go
- pkg/runctl/run_manager.go
- test/builder/pipelineRun.go
The run controller handles all fields of PipelineRunDetails as if they
are set, although all fields are optional and should not be passed as
Tekton TaskRun parameters if not set. Check for empty/unset values and
pass them to the Tekton TaskRun only if set.
Defining `sequenceNumber` as `int` is not appropriate for an API,
because it can be either 32-bit or 64-bit depending on the compilation
target architecture. For an API the size should be fixed. Use `int32`
instead.
> handle pipeline run details as optional

- pkg/k8s/secrets/mocks/mocks.go
- pkg/k8s/secrets/secretUtils.go
- pkg/k8s/secrets/transformers.go
- pkg/k8s/secrets/transformers_test.go
Instead of defining a rule that transformers must not modify the passed
object and return a pointer to a possibly modified copy, it's much
simpler, efficient and less error prone to let the function just modify
the object passed in. Then the caller is responsible for creating a copy
if needed.
> simplify secret transformer functions

- backend-k8s/steward-system/202_deployment_steward-run-controller.yaml
- backend-k8s/steward-system/202_deployment_steward-tenant-controller.yaml
- pkg/runctl/controller.go
- pkg/runctl/controller_test.go
- pkg/runctl/run_manager.go
Currently an aborted pipeline run stays in state cleaning forever.
This change is fixing it.
> Fix abort not cleaning up

- pkg/k8s/mocks/mocks.go
- pkg/k8s/pipelineRun.go
- pkg/k8s/pipelineRun_test.go
- pkg/runctl/controller.go
- pkg/runctl/controller_test.go
- pkg/runctl/run_manager.go
- pkg/runctl/run_manager_test.go
- test/integrationtest/pipelineRun_testbuilders.go
- test/loadtest/pipelineRun_finishedPipelines_test.go
- test/loadtest/pipelineRun_parallel_test.go
- UpdateState changed to atomic change
- FinishState fixed to set StateDetails correctly and set State to StateFinished
- Only set State to Cleaning if not already on Cleaning
- Proper errror handling for failing changeState
- Proper error handling for finish State
- Clenaup: move finishState to controller
> Fix sync handler synchronization

- pkg/k8s/tenantNamespace.go
The log message is wrong and is confusing since it is also logged in the run controller.
> Removed misleading log message from tenantNamespace.go

- pkg/k8s/mocks/mocks.go
- pkg/k8s/pipelineRun.go
- pkg/k8s/pipelineRun_test.go
- pkg/k8s/tenantNamespace.go
- pkg/runctl/controller.go
- pkg/runctl/run_manager.go
- pkg/runctl/run_manager_test.go
Some log entries are useless without context information like which pipelineRun is affected.
> Added missing context info to log entries

- pkg/apis/steward/v1alpha1/run_types.go
- pkg/runctl/controller.go
Currently a pipeline run which is deleted is not counted in the
_steward_pipelineruns_completed_total_ metric.
This is fixed with this change.
> Add deletion result for clean metrics

- charts/steward/templates/clusterrole-run.yaml
- charts/steward/templates/run-podsecuritypolicy.yaml
This change will make Steward work on clusters where pod security
policies are enabled.
Currently, root users are permitted, but that will changed later.
If pod security policies are not enabled in the cluster, this change
will do no harm.
> Add psp for pipeline runs

- test/builder/pipelineRun.go
- test/framework/pipelineRun_helper.go
- test/framework/pipelineRun_helper_test.go
- test/framework/pipelineRun_testbuilders.go
- test/framework/pipelineRun_testbuilders_test.go
- test/integrationtest/pipelineRun_testbuilders.go
Add elastic search details to the pipeline runs of the integration tests.
This enables the logging to elastic search.
> Enable elasticsearch details inx integration tests

- go.mod
- go.sum
- test/framework/client_creator.go
- test/framework/context.go
- test/framework/context_test.go
- test/framework/pipelineRun_helper.go
- test/integrationtest/pipelineRun_testbuilders.go
Improve runID details for the integration tests.
- change key of test name from buildId to jobId 
- add buildId for a single pipeline run
- add realmId for the complete test execution
> Improve runID in integration tests

- charts/steward/templates/podsecuritypolicy-run.yaml
When changing the API group of a PodSecurityPolicy resource object from
`extensions/v1beta1` to `policy/v1beta1`, the Helm upgrade from a
previous Helm chart version fails with:
```
Error: UPGRADE FAILED: rendered manifests contain a new resource that
already exists. Unable to continue with update: existing resource
conflict: namespace: , name: steward-run, existing_kind: policy/v1beta1,
Kind=PodSecurityPolicy, new_kind: policy/v1beta1, Kind=PodSecurityPolicy
```
Revert to API group `extensions/v1beta1`.
> fix: chart: don't change PSP API group

- hack/update-codegen.sh
For some reason on some environments gomock generates
comment lines ending with a period, in other environments
without a period. Until we figured out what the reason is
this change excludes comment lines from the diff.
> Fix codegen --verify

- charts/steward/templates/podsecuritypolicy-run.yaml
apparmor is not supported on gardener cluster. These settings need to be removed, because otherwise pods are stuck in status: blocked.
> Remove apparmor profiles

- hack/update-codegen.sh
The latest master version of mockgen generates the trailing periods. I have version v1.4.3 which does not generate them.
Without `GO111MODULE=on` `go get` will install the latest version from the master branch of a module. With, it is possible to specify the module release tag. This caused the issue of unexpected, different mock generations.
> Fix mockgen issue with trailing dot

- hack/bootstrap-codegen.sh
If the local Git repository of code-generator is outdated, an upgrade to
a newer `K8S_VERSION` may result in an error when checking out the
respective tag.
This can be avoided by fetching tags from origin before.
> bootstrap-codegen: fetch latest tags of code-generator

- charts/steward/templates/clusterrole-run-controller.yaml
- charts/steward/templates/clusterrole-run.yaml
Run controller needs permissions to read/write/edit events.
The service account in the run-namespace needs permissions to watch events.
> Add missing permissions for events

- charts/steward/values.yaml
During load tests the pipeline run controller was OOM-killed. Also, CPU utilization was constantly at around 50m.
Increase the memory to 128Mi and CPU requests to 100m.
> adjust run controller resources

- build.sh
The `go version` command omits the patch version completely if it is
zero, e.g.
$ go version
go version go1.14 linux/amd64
> build.sh: fix: go version check fails if patch is missing

- charts/steward/README.md
- charts/steward/templates/deployment-run-controller.yaml
- charts/steward/values.yaml
- cmd/run_controller/main.go
- docs/monitoring/README.md
- pkg/k8s/pipelineRun.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- pkg/runctl/controller.go
This change contains:
- 2 additional metrics
- to monitor the update times of pipeline-runs
- to monitor the queue length of the pipeline run controller
- 2 additional parameters to the run controller to set qps and burst limits
The helm chart is adjusted to be able to configure qps and burst limits for the run controller.
> Make qps and burst configurable to avoid long waiting times

- charts/steward/values.yaml
Investigated by @valiparsa 
> During loadtest execution we observed that when there are too many finished pipelinerun objects in the cluster run_controller goes into "CrashLoopBackOff" state with the reason of "OOMKilled".
> After some investigation we found that around 13 KB memory is required for the run_controller to process each pipelinerun object in the cluster which means if there are 9846 finished pipelinerun objects in the cluster run_controller can face out of memory issue and crash. To be in a safer side we need to increase it to 256 MB to not face OOM soon.
> Increase RunController Memory Limit

- charts/steward/README.md
- charts/steward/templates/deployment-run-controller.yaml
- charts/steward/values.yaml
- cmd/run_controller/main.go
- go.mod
- pkg/k8s/pipelineRun.go
- pkg/runctl/controller.go
Since also every finished PipelineRun is "processed" by the Run Controller this produces 3 unnecessary log entries per PipelineRun, every 30 seconds. This will let the logs explode.
> Reduce run controller logging

- docs/testing/PermissionTests.md
The content in docs/testing/PermissionTests.md was pointing to non-existing README.md.
> Fix broken hyperlink

- charts/steward/templates/deployment-tenant-controller.yaml
Last version a argument was added to tenant controller, but the command was not specified, which leads to the error: `Error: failed to start container "controller": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-v=2\": executable file not found in $PATH": unknown`
> fix tenant controller

- changelog.yaml
- charts/steward/templates/clustertask-jenkinsfile-runner.yaml
With the upgrade of the Tekton ClusterTask custom resource from v1alpha1 to v1beta1 the `params` field is no longer a child of `inputs` but resides directly under `spec`. This change adapts Steward's ClusterTask `jenkinsfile-runner` accordingly.
No changes in dependencies.
> Fix: ClusterTask does not comply with schema

- changelog.yaml
Add some helpful comments to the changelog.yaml
N/A
Trivial change. No changelog entry necessary.
> Improved comments in changelog.yaml

- .github/PULL_REQUEST_TEMPLATE.md
2 mandatory approvals blocks most pull requests unnecessarily. I would switch to 1 mandatory approval for merging it.
N/A
- N/A [/charts/steward/Chart.yaml](https://github.com/SAP/stewardci-core/blob/master/charts/steward/Chart.yaml) (`version` and `appVersion`)
> Allow PR merge with one approval only

- .reuse/dep5
- changelog.yaml
- charts/steward/templates/deployment-run-controller.yaml
- charts/steward/templates/deployment-tenant-controller.yaml
- charts/steward/values.yaml
- pkg/featureflag/flags.go
- pkg/featureflag/testing/testing.go
- pkg/featureflag/types.go
- pkg/featureflag/types_test.go
- Go package to define and check feature flags
- Helm chart enhancement: inject feature flags into controllers
via environment variable
The Go implementation is based on [kops' featureflag package][1].
[1]: https://github.com/kubernetes/kops/tree/v1.18.1/pkg/featureflag
No dependency changes.
> add feature flag support

- changelog.yaml
- pkg/apis/steward/v1alpha1/run_types.go
Fix struct field tag syntax for `"pkg/apis/steward/v1alpha1".JenkinsfileRunnerSpec`
N/A
> fix: struct tag not compatible with reflect.StructTag

- changelog.yaml
- pkg/runctl/controller.go
- pkg/runctl/controller_test.go
Remove finalizer from pipeline run when cleaning step is done. This avoids delays in deleting pipeline run objects, especially when deleting many of them at the same time, e.g. in test systems.
> Delete finalizer when pipeline run is cleaned

- changelog.yaml
- charts/steward/templates/deployment-tenant-controller.yaml
took the wrong value (from run controller) as qps and burst in tenant controller
> fix args qps and burst of tenant contr deployment

- changelog.yaml
- go.mod
- go.sum
- pkg/apis/steward/v1alpha1/constants.go
- pkg/apis/steward/v1alpha1/run_types.go
- pkg/featureflag/flags.go
- pkg/k8s/mocks/mocks.go
- pkg/k8s/pipelineRun.go
- pkg/runctl/controller.go
- pkg/runctl/controller_test.go
- pkg/runctl/run_manager.go
- pkg/runctl/run_manager_test.go
- pkg/stewardlabels/labelling.go
- pkg/stewardlabels/labelling_test.go
- pkg/stewardlabels/propagate.go
- pkg/stewardlabels/propagate_test.go
- pkg/stewardlabels/zzz_utils_for_test.go
- pkg/tenantctl/controller.go
So far for the execution of a single pipeline run a single pipeline run sandbox namespace was used, which encapsulated all the resource objects needed during the execution. The sandbox namespace is an untrusted zone, as user-provided code has access to its contents, e.g. pods and secrets.
With pipeline run log forwarders we plan to deploy an additional service per pipeline run. That service is configured according to the needs of the "owning" pipeline run. The untrusted pipeline code may interact with the service, but must not have access to its configuration, pods, secrets and so on. Obviously such additional services cannot be defined in the pipeline run sandbox namespace.
Therefore, for each pipeline run an auxiliary namespace gets created next to the main sandbox namespace.
This …
> Introduce auxiliary pipeline run namespaces

- changelog.yaml
- pkg/k8s/pipelineRun.go
- pkg/runctl/controller.go
- pkg/runctl/run_manager.go
- pkg/tenantctl/controller.go
Our checkmarx scan failed with some low findings.
> Fix checkmarx findings

- docs/secrets/Secrets.md
The secret yaml in the jenkinsci examples page shows the wrong secret type.
> Warn about wrong usernamePassword secret type

- changelog.yaml
- charts/steward/Chart.yaml
- pkg/apis/steward/v1alpha1/constants.go
- pkg/k8s/mocks/mocks.go
- pkg/k8s/pipelineRun.go
- pkg/k8s/pipelineRun_test.go
- pkg/runctl/controller.go
- pkg/runctl/controller_test.go
- pkg/runctl/run/interfaces.go
- pkg/runctl/run/mocks/mocks.go
- pkg/runctl/run_manager.go
- pkg/runctl/run_manager_test.go
* Problem: from time to time we receive pipeline runs via build syncer with status "FINISHED", but without build result. This is (most likely) caused by non atomic updates (`state` is first changed and persisted, afterwards `result`).
* Before that change a change has been applied to the memory representation and that change was persisted immediatly.
* With that change a change is only applied to the memory representation. Other changes can be applied afterwards. There is a new `Commit()` function which needs to be called for persisting the changes. With that several changes can be persisted in one step. 
Integration tests on mr2 were successfull (with #249)
- [/charts/steward/Chart.yaml](https://github.com/SAP/stewardci-core/blob/master/charts/steward/Chart.yaml) (`version` and …
> [CLOUDCIFEAT1-130] Avoid non atomic updates

- changelog.yaml
- charts/steward/values.yaml
- pkg/k8s/pipelineRun.go
The default log level was increased to 3.
Some small changes in the log output.
> Increase log level

- changelog.yaml
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
The test case "success_when_state_new" failed with the error message: "cannot observe StateItem if StartedAt is not set".
In State new, we need to use the creation timestamp to get the start time.
> fix metering for state new

- changelog.yaml
- pkg/runctl/run.go
- pkg/runctl/run_test.go
The run controller hits a nil pointer dereference issue when a tekton task is finished but has no finished timestamp.
This can happen if e.g. the fetching of an image fails.
> Fix np when tekton finished and timestamp missing

- changelog.yaml
- pkg/k8s/serviceAccountHelper.go
- pkg/k8s/serviceAccountHelper_test.go
- pkg/k8s/serviceAccountManager.go
- pkg/runctl/controller_test.go
- pkg/runctl/run_manager.go
- pkg/runctl/run_manager_test.go
In `pkg.k8s` the functions `(*serviceAccountHelper) GetServiceAccountSecretName` and `(*serviceAccountHelper) GetServiceAccountSecretNameRepeat` swallow errors that can occur when performing K8s API calls.
- N/A (If applicable) Jira backlog item ID added to the PR title and the [changelog.yaml] entry
Before the changes …
> Fix improper error handling

- pkg/tenantctl/config.go
- pkg/tenantctl/config_test.go
Return an error instead.
- N/A [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change) …
> Don't panic on invalid string argument

- test/builder/pipelineRun_test.go
- test/framework/framework_test.go
- test/integrationtest/pipelineRun_testbuilders.go
- test/networkpolicy/pipelineRun_testbuilders.go
- test/shared/constants.go
#290 has introduced compile errors.
- N/A [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change) …
> Fix errors introduced by #290

- changelog.yaml
- charts/steward/Chart.yaml
- charts/steward/crds/pipelineruns.yaml
- charts/steward/crds/tenants.yaml
- charts/steward/templates/clusterrole-client.yaml
- charts/steward/templates/clusterrole-run.yaml
- charts/steward/templates/clusterrole-tenant.yaml
- charts/steward/templates/clusterrolebinding-run-controller.yaml
- pkg/k8s/clientFactory.go
- pkg/k8s/fake/clientFactory.go
- pkg/k8s/fake/clusterRole.go
- pkg/k8s/mocks/mocks.go
- pkg/k8s/serviceAccountManager.go
- pkg/runctl/run_manager_test.go
- pkg/tenantctl/controller.go
- pkg/tenantctl/controller_test.go
Steward used some Kubernetes API versions that are deprecated in newer Kubernetes releases.
The following replacements have been applied:
- `apiextensions.k8s.io/v1beta1` → `apiextensions.k8s.io/v1`
- `rbac.authorization.k8s.io/v1beta1` → `rbac.authorization.k8s.io/v1`
Before the changes are marked as `ready-for-merge`: …
> Remove use of deprecated K8s APIs

- changelog.yaml
- charts/steward/Chart.yaml
- charts/steward/README.md
- charts/steward/templates/deployment-run-controller.yaml
- charts/steward/templates/deployment-tenant-controller.yaml
- charts/steward/values.yaml
- cmd/run_controller/main.go
- cmd/tenant_controller/main.go
When stewardci-core hits a network issue when connecting to API server, it will only recover after 15 min when the default timeout occurs. To improve the situation the timeout should be configurable.
> Make K8s API connection timeout configurable

- changelog.yaml
- pkg/apis/steward/v1alpha1/constants.go
- pkg/k8s/fake/pipelineRun.go
- pkg/k8s/fake/tenant.go
- pkg/runctl/controller.go
- pkg/stewardlabels/labelling.go
- pkg/tenantctl/controller.go
For tests it is required to create/update Steward CROs, but avoid that Steward controllers act on them.
A new label `steward.sap.com/ignore` (without value) instructs Steward controllers to ignore this API object. The label should never be added to an existing API object.
Before the changes are marked as …
> Add ignore label for pipeline runs and tenants

- changelog.yaml
- pkg/runctl/metrics/pipelineruns_periodic.go
- pkg/runctl/metrics/pipelineruns_periodic_test.go
The duration of an observed pipelinerun's current phase is wrongly calculated based on the start of the pipeline run (`status.startedAt`) instead of the start of the current phase (`status.stateDetails.startedAt`).
Consequently no observations are made for phases `preparing` and `waiting`, because there was no start time yet. For observations of phases `cleaning` and `finished` the duration is too long.
- N/A Changelogs read thoroughly, potential impact described, upgrade notes prepared …
> Fix metric `steward_pipelineruns_ongoing_state_duration_periodic_observations_seconds`

- changelog.yaml
- pkg/runctl/controller_test.go
- pkg/runctl/run.go
- pkg/runctl/run_test.go
The start time of phase "running" was set to the start time of the Tekton TaskRun for JFR, which is when the pod has been _created_. But phase "waiting" now covers the time until successful start-up of the containers in the pod, which can be significantly after pod creation, e.g. due to image pull time.
Therefore, the start time of phase "running" is now the start time of the the JRF container.
> Fix start time of phase "running"

- changelog.yaml
- charts/steward/Chart.yaml
- charts/steward/values.yaml
- pkg/runctl/run.go
- pkg/runctl/run_test.go
Steward can now distinguish error_infra, error_config and error_content depending on the RC of the jenkins file runner.
See https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/97
> [CPCCICD-715] improve error code handling

- changelog.yaml
- charts/steward/Chart.yaml
- charts/steward/README.md
- charts/steward/templates/task-jenkinsfile-runner.yaml
- charts/steward/values.yaml
We want to add support for log-forwarders (i.e. fluentd) instead of sending logs directly to OpenSearch/ElasticSearch. For this purpose, two configuration extension for the Helm chart are prepared:
* Set environment variables to configure the elasticsearch-log-plugin to forward data to fluentd
* Enable the use of tekton sidecars. This can be used to run the forwarder as a sidecar container in the JFR pod
Note: With the current version of the JFR image, the plugin fails at startup when configured to use fluentd. This is addressed by this fix: https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/101
Before …
> CPCCICD-1045 Enable log forwarding

- changelog.yaml
- charts/steward/Chart.yaml
- charts/steward/values.yaml
The new image contains updates for Jenkins core (to 2.375.4), all plugins and the base image.
See release note for [version 230810_ab62215](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/230810_ab62215)
> Update JFR image to version 230810_ab62215

- changelog.yaml
- charts/steward/Chart.yaml
- charts/steward/values.yaml
The new image contains updates for Jenkins core (to 2.387.3) and all plugins.
See release note for [version 230822_3c378b2](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/230822_3c378b2)
> Update JFR image to version 230822_3c378b2

- changelog.yaml
- pkg/runctl/secretmgr/secret_manager.go
- pkg/runctl/secretmgr/secret_manager_test.go
In the following cases the preparation of a pipeline run fails with result `error_content`, although it should be `error_config`:
- secrets referenced by pipeline runs don't exist
- multiple secrets map to the same name
- the configured Jenkinsfile repo server URL is invalid
> Use result `error_config` instead of `error_content`

- changelog.yaml
- pkg/runctl/controller.go
logFinalState function does not need to return an error because the error value is always nil.
> Fix: remove redundant error

- changelog.yaml
- go.mod
- go.sum
- pkg/k8s/pipelineRun.go
- pkg/k8s/pipelineRun_test.go
- pkg/runctl/constants/constants.go
- pkg/runctl/controller.go
- pkg/runctl/controller_test.go
- pkg/runctl/run/interfaces.go
- pkg/runctl/run/mocks/mocks.go
- pkg/runctl/runmgr/constants.go
- pkg/runctl/runmgr/helpers_for_test.go
- pkg/runctl/runmgr/run.go
- pkg/runctl/runmgr/run_manager.go
- pkg/runctl/runmgr/run_manager_test.go
- pkg/runctl/runmgr/run_test.go
- Recreate JFR TaskRun if pod creation failed
The creation of the JFR pod may temporarily fail, e.g. due to a
timeout calling a mandatory admission webhook. Steward should detect
this and recreate the Tekton taskrun to retry.
- Stop waiting for finished non-restartable JFR TaskRun
If a JFR TaskRun was never started, is finished and is not
restartable, Steward now fails the PipelineRun instead of waiting
until timeout.
> Improve handling of failed JFR TaskRuns
