docs/examples/pipelinerun_sleep.yaml
Argument was renamed in https://github.com/sap-production/demo-pipelines
=> Fix sleep example

test/README.md, test/clinet_creator.go, test/pipelineRun_conditions_test.go, test/pipelineRun_helper.go, test/pipelineRun_parallel_test.go, test/pipelineRun_test.go, test/pipelineRun_testbuilders.go, test/tenant_test.go, test/wait.go
Allow parallel execution of integration tests
=> Pr integration parallel

pkg/k8s/secrets/secretUtils_test.go
Test that metadata fields are stripped.
=> add test for secrets.CreateSecret

pkg/k8s/secrets/providers/fake/provider.go, pkg/k8s/secrets/providers/k8s/provider.go, pkg/k8s/secrets/providers/utils.go, pkg/k8s/secrets/providers/utils_test.go
remove DeepCopy
remove return value
=> improve secret strip metadata

backend-k8s/steward-system/300_clusterTask_steward-jenkinsfile-runner.yaml
- ES plugin with extended connection timeout
- ES plugin with fixed vulnerability
- latest LTS Jenkins and plugins.
=> Updated JFR image 200108_c7477b7

backend-k8s/steward-system/202_deployment_steward-run-controller.yaml, backend-k8s/steward-system/202_deployment_steward-tenant-controller.yaml
- Improved logging
- fixed schema validation
=> Latest controllers 200114_1b68057

docs/install/README.md, go.mod, go.sum, pkg/runctl/run_manager.go
Upgrade dependency to tekton version v0.8.0
Adjust deprecated ServiceAccount to ServiceAccountName
=> Update tekton to version 0.8.0

charts/steward/templates/_hooks.tpl
In case of multiple CRDs some resources are generated multiple times.
This confuses the diff plug-in for Helm.
=> Helm chart: avoid duplicate hook resources

test/integrationtest/pipelineRun_testbuilders.go
Add run details to integration tests.
See https://github.com/SAP/stewardci-jenkinsfilerunner-image/issues/11
=> Improve tests with run details

test/networkpolicy/.gitignore, test/networkpolicy/README.md, test/networkpolicy/netcat.yaml, test/networkpolicy/open_policy.yaml, test/networkpolicy/pipelineRun_closed_policy_test.go, test/networkpolicy/pipelineRun_open_policy_test.go, test/networkpolicy/pipelineRun_testbuilders.go, test/networkpolicy/run_test.sh
This PR contains integration tests for network policy.
Depends on #80 and #82
=> Network policy integration tests

pkg/k8s/pipelineRun.go, pkg/k8s/pipelineRun_test.go, pkg/runctl/controller.go
This should make the run controller more resilient and fix
https://sapjira.wdf.sap.corp/browse/CLOUDCISERVICE-1041
=> Retry status updates on conflict

charts/steward/Chart.yaml, charts/steward/values.yaml
This chart version contains the fix for:
https://sapjira.wdf.sap.corp/browse/CLOUDCISERVICE-1041
=> New chart version using fixed images

charts/steward/Chart.yaml, docs/development/README.md
Only for releases the -dev will be removed.
=> Introducing -dev version during development

charts/steward/crds/pipelineruns.yaml, charts/steward/crds/tenants.yaml
=> Introduce shortnames for CRDs

charts/steward/values.yaml
see Jenkinsfile Runner Image [Release Notes](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200603_f666776)
=> Update Jenkinsfile Runner to release 200603_f666776

charts/steward/values.yaml
https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200618_0e98da9
=> Updating JFR image to 200618_0e98da9

build.sh, test/framework/framework_test.go, test/framework/tenant_test.go
Fix test compilation error and enhance build.sh to find such errors.
=> fix test compile

charts/steward/values.yaml
https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200624_477b249
=> New JFR image 200624_477b249

charts/steward/values.yaml
See JFR release [200721_525ba95](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200721_525ba95).
=> update JFR image to 200721_525ba95

test/integrationtest/pipelineRun_testbuilders.go
Add an integration test which uses the k8s plugin to detect permission problems.
=> Add k8s plugin integration test

charts/steward/values.yaml
https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200812_0857488
=> New JFR image 200812_0857488

charts/steward/values.yaml
[Release notes](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200814_a42a6c5)
=> Updated JFR image to 200814_a42a6c5

charts/steward/values.yaml
[Release notes](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200826_aa1e67d)
=> New JFR image 200826_aa1e67d - with curl

charts/steward/values.yaml
See [200903_b053f5f release notes](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/200903_b053f5f).
The changes do not require any adaptations.
=> use Jenkinsfile Runner image 200903_b053f5f

docs/development/README.md
=> Minor docu improvement

pkg/k8s/pipelineRun.go, pkg/k8s/pipelineRun_test.go
See the individual commits for details.
=> Improve k8s.pipelineRun

changelog.html, index.html
Dynamic changelog.html which reads the changelog.yaml from the master branch and renders the changelog better readable.
=> Add dynamic changelog.html to gh_pages

README.md
A link to the dynamic changelog has been added to the README.md.
N/A
Trivial change
=> Add changelog link to README

changelog.yaml
We need to change all `>-` to `|-` in order to keep the newlines of markdown blocks.
N/A
In case dependencies have been updated: No
=> Keep markdown new lines in changelog.yaml

changelog.yaml, charts/steward/README.md, charts/steward/data/pipelineruns-default-networkpolicy.yaml, charts/steward/templates/clustertask-jenkinsfile-runner.yaml, charts/steward/values.yaml, docs/development/README.md, docs/pipeline-logs-elasticsearch/README.md, test/networkpolicy/open_policy_aws.yaml, test/networkpolicy/open_policy_gcp.yaml
Replace insensitive terms with inclusive language
N/A
=> Replace insensitive terms with inclusive language

changelog.yaml, pkg/runctl/cfg/config.go, pkg/runctl/cfg/config_test.go, pkg/runctl/run_manager.go, pkg/runctl/run_manager_test.go
- Do not exclude the default network policy from `PipelineRunsConfigStruct.NetworkPolicies`.
- Do not trim network policy values (could invalidate correct original values, e.g. if all lines are indented).
- `LoadPipelineRunsConfig`:
- Fail if the network policies config map does not exist (having no network policy would forbid any network traffic for pipeline run pods, which in turn would always fail).
- Give more precise error messages in case of erroneous pipeline run configuration.
- Put the key of the default network policy instead of its value into a `PipelineRunsConfigStruct`.
- Lots of refactorings.
N/A
- ee5de92
In case dependencies have been …
=> polish pkg/runctl/cfg

changelog.yaml, go.mod, go.sum
Upgrade github.com/aws/aws-sdk-go from v1.32.1 to v1.34.1
Upgrade github.com/aws/aws-sdk-go from v1.32.1 to v1.34.1
- stewardci/stewardci-run-controller:TEST_201111_d302c7e tested OK
=> Upgrade github.com/aws/aws-sdk-go from v1.32.1 to v1.34.1

build.sh, test/framework/pipelineRun_helper.go
Enhance `build.sh` to run `go vet`.
=> build.sh: run `go vet`

.github/PULL_REQUEST_TEMPLATE.md, changelog.yaml
Our generic PR template and changelog template changed. The changes are applied using this pull request.
N/A
=> Applied latest PR template and changelog changes

changelog.yaml
The changelog has been broken. The new validation checks fail (and will prevent such issues right from the PR now).
N/A
ℹ Minor internal change - no changelog entry.
=> Fix broken changelog.yaml

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge via pipeline failed due to branch protection. Pipeline needs to be adjusted.
=> Merge v0.6.2 back into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.6.3 into PR_pipelineUpdate_test
=> Merge release 0.6.3 into PR_pipelineUpdate_test

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.6.3 into master
=> Merge release 0.6.3 into master

.github/PULL_REQUEST_TEMPLATE.md, changelog.yaml
=> Update PR template and changelog

changelog.yaml, pkg/k8s/pipelineRun.go, pkg/k8s/pipelineRun_test.go
=> [CLOUDCI-467] Fix update state history

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Update Jenkinsfile-runner image to a newer version.
Updates since last released version can be found [here](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/210202_42eb583)
=> Update JFR image

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.7.0 into master
=> Merge release 0.7.0 into master

changelog.yaml
=> Fix changelog.yaml

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.8.0 into master
=> Merge release 0.8.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.8.1 into master
=> Merge release 0.8.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.8.2 into master
=> Merge release 0.8.2 into master

changelog.yaml, charts/steward/values.yaml
Updated JFR image to 210413_777e270 with `agentProtocols` config & latest ES plugin (actually no real changes in the plugin):
https://github.com/SAP/stewardci-jenkinsfilerunner-image/compare/210205_1988c5e...210413_777e270
=> Update JFR image to 210413_777e270

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.8.3 into master
=> Merge release 0.8.3 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
See https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/61
The Jenkinsfile Runner image has been updated to [210518_50469d1](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/210518_50469d1).
This image version contains an updated LTS Jenkins Core version 2.277.4, updated plugins and an updated Jenkinsfile Runner 1.0-beta-27 with
[steward specific adjustments](https://github.com/SAP/stewardci-jenkinsfilerunner-image/tree/jenkinsfile-runner--1.0-beta-27-steward-1). …
=> Update JFR image to 210518_50469d1

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.9.0 into master
=> Merge release 0.9.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.10.0 into master
=> Merge release 0.10.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.11.0 into master
=> Merge release 0.11.0 into master

changelog.yaml, charts/steward/values.yaml
&lt;Add detailed description for reviewers here.&gt;
=> Update JenkinsfileRunner image to 210728_f8be088

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.12.0 into master
=> Merge release 0.12.0 into master

changelog.yaml, pkg/runctl/controller.go, pkg/runctl/controller_test.go
=> Fix deletion bug

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.12.1 into master
=> Merge release 0.12.1 into master

test/integrationtest/pipelineRun_testbuilders.go
Integration test was running in a timeout as retry was introduced in the jenkins filerunner.
See also https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/68
Timeout is increased and result is checked instead of long message with lot of retries.
=> Adjust integration test to retry for pipeline clone

changelog.yaml, pkg/runctl/controller.go, pkg/runctl/controller_test.go
Fix edge cases of https://github.com/SAP/stewardci-core/issues/241
Integrationtests executed successfully on mr2
=> Fix deletion problem

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.13.0 into master
=> Merge release 0.13.0 into master

changelog.yaml, charts/steward/values.yaml
This change updates the JFR image to [210924_6ec1ff6](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/210924_6ec1ff6) with latest Jenkins Core and plugins.
=> Update JFR image to 210924_6ec1ff6

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.13.1 into master
=> Merge release 0.13.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.13.2 into master
=> Merge release 0.13.2 into master

changelog.yaml, docs/examples/network_profile/pipelinerun_network.yaml, docs/examples/network_profile/pipelinerun_network_blocked.yaml, docs/examples/network_profile/pipelinerun_network_internet.yaml, docs/examples/network_profile/pipelinerun_network_unknown.yaml, docs/examples/pipelinerun_count.yaml, docs/examples/pipelinerun_details.yaml, docs/examples/pipelinerun_error.yaml, docs/examples/pipelinerun_gitscm.yaml, docs/examples/pipelinerun_image.yaml, docs/examples/pipelinerun_k8s_plugin.yaml, docs/examples/pipelinerun_ok.yaml, docs/examples/pipelinerun_sleep.yaml, docs/examples/pipelinerun_wrong_git_url.yaml, docs/examples/secrets/pipelinerun_missing_secret.yaml, docs/examples/secrets/pipelinerun_secret_rename.yaml
=> GitHub renamed sample master branch to main

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.14.2 into master
=> Merge release 0.14.2 into master

changelog.yaml, pkg/runctl/controller.go
=> [CLOUDCI-1131] fix heartbeat

build.sh, changelog.yaml
Prepare `build.sh` for Go v1.16+.
=> Prepare build.sh for Go v1.16+.

changelog.yaml, charts/steward/values.yaml
Updated JFR to [211116_03f24d5](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/211116_03f24d5)
=> Update JFR to 211116_03f24d5

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.14.4 into master
=> Merge release 0.14.4 into master

changelog.yaml, cmd/run_controller/main.go, cmd/tenant_controller/main.go
Change the panic behaviour of the controllers to a proper exit behaviour.
=> Don't panic but exit gracefully

docs/monitoring/Metrics Reference.md, pkg/metrics/k8srestclient/ratelimit_latency.go, pkg/metrics/k8srestclient/ratelimit_latency_test.go, pkg/metrics/k8srestclient/register.go, pkg/metrics/k8srestclient/utils.go
This is an extension of #282. After updating client-go, a new REST client metric for client-side rate limit latency can be exposed.
As #282 is not released yet, no additional changelog entry is required.
- N/A] (If applicable) Jira backlog item ID added to the PR title and the [changelog.yaml] entry
- N/A [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change)
- N/A Changelogs read …
=> Add metric `steward_k8sclient_rest_ratelimit_latency_millis`

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.15.0 into master
=> Merge release 0.15.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/README.md, charts/steward/templates/deployment-run-controller.yaml, charts/steward/templates/deployment-tenant-controller.yaml, charts/steward/values.yaml, cmd/run_controller/main.go, cmd/tenant_controller/main.go, docs/monitoring/Metrics Reference.md, pkg/runctl/controller.go, pkg/runctl/controller_test.go, pkg/runctl/metrics/controller_heartbeats.go, pkg/runctl/metrics/controller_heartbeats_test.go, pkg/tenantctl/controller.go, pkg/tenantctl/controller_test.go, pkg/tenantctl/metrics/controller_heartbeats.go, pkg/tenantctl/metrics/controller_heartbeats_test.go, pkg/tenantctl/metrics/generic.go
- Add heartbeat for tenant controller
- Introduce heartbeat counter metrics
- Make heartbeat configurable via command line options
- Make heartbeat configurable via Helm chart parameters
- Handle heartbeat in function `syncHandler`, not `processNextWorkItem`, to make the heartbeat call more similar to normal work item processing.
- N/A Check if dependency updates affect our semantic version …
=> Improve controller heartbeat

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.16.0 into master
=> Merge release 0.16.0 into master

changelog.yaml, charts/steward/templates/_hooks.tpl, charts/steward/values.yaml
So far `kubectl apply` has been used to create or update CRDs. But in case of updating an existing CRD the result may be a mixture of existing and new CRD that is possibly broken.
Now `kubectl create` and `kubectl replace` are used instead.
[changelog.yaml]: …
=> Helm chart: Fix CRD updates

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.16.1 into master
=> Merge release 0.16.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.17.0 into master
=> Merge release 0.17.0 into master

changelog.yaml, charts/steward/values.yaml
Updated JFR image [211220_cf0ea4a](https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/211220_cf0ea4a) with latest plugins and core.
=> Update Jenkinsfile Runner image to 211220_cf0ea4a

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.17.1 into master
=> Merge release 0.17.1 into master

.github/workflows/codeql-analysis.yml
This change activates the [code scanning alerts](https://github.com/SAP/stewardci-core/security).
=> Enable GitHub CodeQL code scanning alerts

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.18.0 into master
=> Merge release 0.18.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.18.1 into master
=> Merge release 0.18.1 into master

changelog.yaml, charts/steward/values.yaml
new JFR image with updated Jenkins Core, plugins and adoptopenjdk base image. Fixes some vulnerabilities.
https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/220124_2022975
=> Updated JFR to 220124_2022975

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.18.2 into master
=> Merge release 0.18.2 into master

changelog.yaml, charts/steward/values.yaml
https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/220215_5d89c43
Plugins, Jenkins Core and base image updated.
=> Update JFR image to 220215_5d89c43

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.18.3 into master
=> Merge release 0.18.3 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.18.4 into master
=> Merge release 0.18.4 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/crds/pipelineruns.yaml, docs/backend-api/README.md, docs/examples/pipelinerun_timeout.yaml, pkg/apis/steward/v1alpha1/run_types.go, pkg/apis/steward/v1alpha1/zz_generated.deepcopy.go, pkg/runctl/run_manager.go, pkg/runctl/run_manager_test.go
&lt;Add detailed description for reviewers here.&gt;
=> CLOUDCI-1286: Add build timeout to pipeline run context

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.19.0 into master
=> Merge release 0.19.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.19.1 into master
=> Merge release 0.19.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.20.0 into master
=> Merge release 0.20.0 into master

changelog.yaml, charts/steward/values.yaml
https://github.com/SAP/stewardci-jenkinsfilerunner-image/releases/tag/220701_94864a5
=> Updated JFR image to 220701_94864a5

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.21.1 into master
=> Merge release 0.21.1 into master

changelog.yaml, charts/steward/values.yaml
The memory limit of the Steward Tenant Controller container has been found to be too low. It should be higher to avoid OOM kills.
=> Increase Steward Tenant Controller memory limit

changelog.yaml, charts/steward/values.yaml
Merge PR #332 with squashed commits.
=> Increase tekton memory

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.21.2 into master
=> Merge release 0.21.2 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.22.0 into master
=> Merge release 0.22.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.22.1 into master
=> Merge release 0.22.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/templates/clusterrole-aggregate.yaml, charts/steward/templates/clusterroles-crds.yaml
Add aggregate cluster roles for the view, edit and admin role for tenants and pipelineruns.
=> add aggregated cluster roles for crds

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.23.0 into master
=> Merge release 0.23.0 into master

changelog.yaml, charts/steward/values.yaml
We have a new version of our jenkinsfile-runner which can now use in stewardci-core.
=> Update 'stewardci-jenkinsfile-runner' image to version 221118_24e6615

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.23.1 into master
=> Merge release 0.23.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.24.0 into master
=> Merge release 0.24.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.24.1 into master
=> Merge release 0.24.1 into master

changelog.yaml
We had to apply a hotfix. The changes now need to be merged back into the master branch.
=> Merge hotfix into master branch

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.25.0 into master
=> Merge release 0.25.0 into master

changelog.yaml, charts/steward/values.yaml
=> Rollback JFR plugin update

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.25.1 into master
=> Merge release 0.25.1 into master

changelog.yaml, charts/steward/values.yaml
Use Jenkins 2.346.3 with [updated plugins](https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/98).
Including the use of the [compatible kubernetes related plugins](https://github.com/SAP/stewardci-jenkinsfilerunner-image/pull/100).
In addition, the base images was updated to include updating some alpine packages updates.
=> [JFR] Update JFR image to version 230201_c535874

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.25.2 into master
=> Merge release 0.25.2 into master

changelog.yaml, pkg/runctl/controller.go, pkg/runctl/controller_test.go
Improve readability of message on wait timeout.
=> improve message

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.26.0 into master
=> Merge release 0.26.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.27.0 into master
=> Merge release 0.27.0 into master

pkg/k8s/mocks/client-go/corev1/mocks.go, pkg/k8s/mocks/mocks.go, pkg/k8s/pipelineRun.go, pkg/k8s/pipelineRun_test.go, pkg/k8s/secrets/mocks/mocks.go, pkg/runctl/controller.go, pkg/runctl/controller_test.go, pkg/runctl/metrics/testing/mocks.go, pkg/runctl/run/mocks/mocks.go, pkg/runctl/runmgr/helpers_for_test.go, pkg/runctl/secretmgr/secret_manager.go, pkg/runctl/secretmgr/secret_manager_test.go
=> Further refactorings for #371

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.27.2 into master
=> Merge release 0.27.2 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.29.0 into master
=> Merge release 0.29.0 into master

changelog.yaml, charts/steward/values.yaml
=> [CPCCICD-1125] Update jenkinsfileRunner image

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.29.1 into master
=> Merge release 0.29.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.30.0 into master
=> Merge release 0.30.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.31.0 into master
=> Merge release 0.31.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Use JFR image with --no-build-logs option.
Build logs are either written to stdout or forwarded to OpenSearch.
=> Update jenkinsfile-runner image

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.32.0 into master
=> Merge release 0.32.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.33.0 into master
=> Merge release 0.33.0 into master

pkg/signals/signal.go
- Same log message is used multiple times and should be deduplicated.
- ~[ ] [changelog.yaml] entry with upgrade notes is prepared and appropriate for the audience affected by the change (users or developer, depending on the change)~
- ~[ ] Links to external changelogs, since the last release of our component, added to the [changelog.yaml] entry (description).~
- ~[ ] Changelogs read thoroughly, potential impact described, upgrade notes prepared (if necessary)~
- ~[ ] Check if dependency updates affect our semantic version increment.~
[changelog.yaml]: …
=> Fix issues found by Sonar

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.34.0 into master
=> Merge release 0.34.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.35.0 into master
=> Merge release 0.35.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.36.0 into master
=> Merge release 0.36.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/templates/_helpers.tpl, charts/steward/templates/task-jenkinsfile-runner.yaml, charts/steward/values.yaml
Update Jenkinsfile-runner image and make more elasticsearch-logs-plugin configurable in the Helm chart
=> Update JFR image and make logs plugin params configurable

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.37.0 into master
=> Merge release 0.37.0 into master

changelog.yaml, charts/steward/values.yaml
Update JFR image to tag 231018_94c7e9a
=> Update JFR image to tag 231018_94c7e9a

.dockerignore, changelog.yaml, cmd/run_controller/Dockerfile
Small improvements to container build files.
=> Tweak container build

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.39.0 into master
=> Merge release 0.39.0 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.39.1 into master
=> Merge release 0.39.1 into master

changelog.yaml, charts/steward/Chart.yaml, charts/steward/README.md, charts/steward/templates/_hooks.tpl, charts/steward/templates/deployment-run-controller.yaml, charts/steward/templates/task-jenkinsfile-runner.yaml, charts/steward/values.yaml
Add security context to hooks to be able to set restricted profile for `steward-system` namespace.
This is preparation for k8s v1.25+.
=> Add security context to hooks

changelog.yaml, charts/steward/Chart.yaml, charts/steward/values.yaml
Merge release 0.40.0 into master
=> Merge release 0.40.0 into master
